name: Build and Deploy Nest.js - frontend

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types:
      - closed

# env:
#   APP_ENV: next-js-action
#   ECR_NAME: my-backend-test

jobs:
  Main-Branch-build-deploy-nextjs:
    name: Main-Branch-build-deploy
    environment: main 
    # if: github.ref == 'refs/heads/main' && github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true || github.event_name == 'push'
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Next.js app
      run: npm run build

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}

    - name: Make zip file # aws s3 cp .next s3://github-action-org-jh/next-js-action/.next --recursive
      run: |
        mkdir deploy
        zip -r deploy.zip .

    - name: Upload to S3 # aws s3 cp .next s3://github-action-org-jh/next-js-action/.next --recursive  ./next 복사
      run: |        
        aws s3 cp deploy.zip s3://github-action-org-jh/next-js-action/main/deploy-app.zip 

    - name: Code Deploy
      run: |
        aws deploy create-deployment --application-name next-js-sample-jh --deployment-group-name github-action-org --s3-location bucket=github-action-org-jh,bundleType=zip,key=next-js-action/deploy-app.zip --output json


  DEV-Branch-build-deploy-nextjs:
    name: DEV-Branch-build-deploy
    environment: dev 
    if: github.ref == 'refs/heads/dev'
    # if: github.ref == 'refs/heads/dev' && github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Next.js app
      run: npm run build

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}

    - name: Make zip file # aws s3 cp .next s3://github-action-org-jh/next-js-action/.next --recursive
      run: |
        mkdir deploy
        zip -r deploy.zip .

    - name: Upload to S3 # aws s3 cp .next s3://github-action-org-jh/next-js-action/.next --recursive  ./next 복사
      run: |        
        aws s3 cp deploy.zip s3://github-action-org-jh/next-js-action/dev/deploy-app.zip 

    - name: Code Deploy
      run: |
        aws deploy create-deployment --application-name next-js-sample-jh --deployment-group-name github-action-org --s3-location bucket=github-action-org-jh,bundleType=zip,key=next-js-action/deploy-app.zip --output json
